---
- name: creating mailserver MySQL database
  mysql_db: name=mailserver login_user=root login_password={{mysql_root_password}} state=present
- name: creating Roundcube MySQL database
  mysql_db: name=roundcube login_user=root login_password={{mysql_root_password}} state=present
- name: copying MySQL database schema to server
  copy: src=schema.sql dest=/tmp
- name: setting up SQL schema of mailserver database
  mysql_db: name=mailserver login_user=root login_password={{mysql_root_password}} state=import target=/tmp/schema.sql
- name: creating MySQL user to read the mailserver database
  mysql_user:
    name: mailuser
    password: "{{ispmail_mysql_mailuser_password}}"
    priv: "mailserver.*:SELECT,INSERT,UPDATE,DELETE"
    state: present
  notify:
  - restart mysql
- name: creating MySQL user for roundcube
  mysql_user:
    name: roundcube
    password: "{{ispmail_mysql_roundcube_password}}"
    priv: "roundcube.*:ALL"
    state: present
  notify:
  - restart mysql
